---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/1/14 10:58
---
-- 参数列表
-- 1.1 优惠券id
local voucherId = ARGV[1]
-- 1.2 用户id
local userId = ARGV[2]

-- 2数据key
-- 2.1库存key
local stockKey = "seckill:stock:" .. voucherId
-- 2.2订单key
local orderKey = "seckill:order:" .. voucherId

-- 3.业务脚本
if(tonumber(redis.call("get", stockKey)) <= 0 ) then
    -- 库存不足 返回1
    return 1
end
if(redis.call("sismember", orderKey, userId) == 1) then
    -- 用户已经购买过 返回2
    return 2
end
-- 扣减库存
redis.call("incrby", stockKey, -1)
-- 保存用户的订单到redis
redis.call("sadd", orderKey, userId)
--返回0
return 0